const prefix = '@AdventuresContainer/';

export default {
  GET_ADVENTURES: `${prefix}GET_ADVENTURES`,
  GET_ADVENTURES_REQUEST: `${prefix}GET_ADVENTURES_REQUEST`,
  GET_ADVENTURES_REQUEST_SUCCESS: `${prefix}GET_ADVENTURES_REQUEST_SUCCESS`,
  GET_ADVENTURES_REQUEST_ERROR: `${prefix}GET_ADVENTURES_REQUEST_ERROR`
};
